[2025-02-27T21:34:50.086+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_db_dag.process_raw_velib_station manual__2025-02-27T21:34:45.826088+00:00 [queued]>
[2025-02-27T21:34:50.091+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_db_dag.process_raw_velib_station manual__2025-02-27T21:34:45.826088+00:00 [queued]>
[2025-02-27T21:34:50.092+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-02-27T21:34:50.100+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): process_raw_velib_station> on 2025-02-27 21:34:45.826088+00:00
[2025-02-27T21:34:50.104+0000] {standard_task_runner.py:57} INFO - Started process 3233 to run task
[2025-02-27T21:34:50.106+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_to_db_dag', 'process_raw_velib_station', 'manual__2025-02-27T21:34:45.826088+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpnbvubjts']
[2025-02-27T21:34:50.108+0000] {standard_task_runner.py:85} INFO - Job 61: Subtask process_raw_velib_station
[2025-02-27T21:34:50.146+0000] {task_command.py:410} INFO - Running <TaskInstance: api_to_db_dag.process_raw_velib_station manual__2025-02-27T21:34:45.826088+00:00 [running]> on host 53fdc8261bae
[2025-02-27T21:34:50.364+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_to_db_dag' AIRFLOW_CTX_TASK_ID='process_raw_velib_station' AIRFLOW_CTX_EXECUTION_DATE='2025-02-27T21:34:45.826088+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-27T21:34:45.826088+00:00'
[2025-02-27T21:34:50.414+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 27, in process_files_in_directory
    function(full_path)
  File "/opt/airflow/dags/dag.py", line 129, in format_velib_data
    final_df.to_parquet(formatted_path, compression='snappy')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 2685, in to_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 423, in to_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 180, in write
    is_dir=partition_cols is not None,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 102, in _get_path_or_handle
    path_or_handle, mode, is_text=False, storage_options=storage_options
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 711, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/data/formatted/velib_api/velib_stations/202502272101/extract.snappy.parquet'
[2025-02-27T21:34:50.423+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=api_to_db_dag, task_id=process_raw_velib_station, execution_date=20250227T213445, start_date=20250227T213450, end_date=20250227T213450
[2025-02-27T21:34:50.430+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 61 for task process_raw_velib_station ([Errno 2] No such file or directory: '/mnt/data/formatted/velib_api/velib_stations/202502272101/extract.snappy.parquet'; 3233)
[2025-02-27T21:34:50.450+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-02-27T21:34:50.467+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
