[2025-03-02T19:21:24.930+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_db_dag.process_raw_velib_station manual__2025-03-02T19:21:12.961321+00:00 [queued]>
[2025-03-02T19:21:24.997+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_db_dag.process_raw_velib_station manual__2025-03-02T19:21:12.961321+00:00 [queued]>
[2025-03-02T19:21:24.999+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-03-02T19:21:25.068+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): process_raw_velib_station> on 2025-03-02 19:21:12.961321+00:00
[2025-03-02T19:21:25.169+0000] {standard_task_runner.py:57} INFO - Started process 79537 to run task
[2025-03-02T19:21:25.222+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_to_db_dag', 'process_raw_velib_station', 'manual__2025-03-02T19:21:12.961321+00:00', '--job-id', '201', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpe4m85f0m']
[2025-03-02T19:21:25.235+0000] {standard_task_runner.py:85} INFO - Job 201: Subtask process_raw_velib_station
[2025-03-02T19:21:25.401+0000] {task_command.py:410} INFO - Running <TaskInstance: api_to_db_dag.process_raw_velib_station manual__2025-03-02T19:21:12.961321+00:00 [running]> on host 3befbd719c1b
[2025-03-02T19:21:25.647+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_to_db_dag' AIRFLOW_CTX_TASK_ID='process_raw_velib_station' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T19:21:12.961321+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-02T19:21:12.961321+00:00'
[2025-03-02T19:21:25.727+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011730.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011730.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:25.860+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503010009.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503010009.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:26.046+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011100.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011100.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:26.090+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011415.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011415.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:26.137+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011045.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011045.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:26.163+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011815.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011815.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:26.193+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503010005.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503010005.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:26.212+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503010012.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503010012.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:26.255+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011615.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011615.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:26.278+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011245.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011245.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:26.307+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503010004.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503010004.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:26.338+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011300.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011300.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:26.362+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011930.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011930.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:26.385+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011530.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011530.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:26.422+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503012035.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503012035.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:26.610+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011215.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011215.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:26.635+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011645.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011645.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:26.670+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011130.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011130.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:26.690+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011330.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011330.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:27.399+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503010940.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503010940.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:27.430+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503010002.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503010002.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:27.478+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503010901.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503010901.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:27.515+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011845.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011845.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:27.550+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011900.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011900.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:27.594+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011500.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011500.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:27.618+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011015.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011015.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:27.664+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011445.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011445.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:27.687+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011702.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011702.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:27.713+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503010902.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503010902.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:27.828+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011000.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011000.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:27.848+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011515.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011515.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:27.861+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011145.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011145.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:27.896+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011915.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011915.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:27.954+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011630.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011630.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:28.061+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011830.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011830.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:28.097+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011430.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011430.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:28.131+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503010000.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503010000.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:28.163+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011715.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011715.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:28.185+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011345.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011345.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:28.223+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011200.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011200.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:28.321+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011030.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011030.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:28.424+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011548.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011548.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:28.481+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011315.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011315.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:28.520+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011745.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011745.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:28.554+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011600.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011600.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:28.572+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503010011.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503010011.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:28.626+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503010945.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503010945.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:28.733+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011945.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011945.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:28.762+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011800.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011800.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:28.873+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011400.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011400.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:29.030+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011115.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011115.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:29.084+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503010006.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503010006.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:29.130+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503010010.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503010010.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:29.203+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011230.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011230.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:29.288+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282010.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282010.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:29.859+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281954.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281954.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:29.882+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282102.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282102.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:29.912+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281942.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281942.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:29.938+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282114.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282114.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:29.963+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281915.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281915.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:29.982+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282006.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282006.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:30.005+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282342.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282342.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:30.025+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281958.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281958.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:30.044+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281348.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281348.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:30.063+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282026.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282026.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:30.099+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282030.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282030.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:30.138+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282318.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282318.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:30.167+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281922.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281922.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:30.212+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281758.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281758.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:30.262+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281934.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281934.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:30.306+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282359.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282359.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:30.347+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281918.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281918.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:30.370+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282322.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282322.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:30.406+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282230.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282230.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:30.567+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282158.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282158.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:30.589+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282206.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282206.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:30.613+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282314.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282314.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:30.668+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282302.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282302.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:30.691+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281938.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281938.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:30.706+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282210.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282210.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:30.720+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282050.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282050.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:30.745+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281739.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281739.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:30.770+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282046.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282046.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:30.789+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282338.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282338.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:30.824+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281909.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281909.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:30.843+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281231.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281231.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:30.890+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282108.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282108.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:30.914+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281732.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281732.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:30.933+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281948.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281948.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:30.955+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282020.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282020.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:30.990+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282036.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282036.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:31.035+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282016.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282016.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:31.050+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281952.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281952.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:31.065+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281817.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281817.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:31.083+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282104.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282104.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:31.099+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281728.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281728.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:31.113+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281944.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281944.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:31.124+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282112.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282112.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:31.138+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282000.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282000.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:31.149+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282256.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282256.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:31.166+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282344.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282344.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:31.186+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281354.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281354.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:31.200+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282200.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282200.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:31.217+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282312.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282312.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:31.233+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281928.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281928.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:31.584+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282304.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282304.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:31.621+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282216.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282216.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:31.645+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281338.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281338.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:31.672+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282328.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282328.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:31.699+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282056.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282056.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:31.743+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282040.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282040.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:31.773+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281924.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281924.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:31.820+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282308.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282308.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:31.844+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281932.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281932.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:31.869+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281436.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281436.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:31.887+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282324.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282324.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:31.925+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282236.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282236.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:31.961+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282220.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282220.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:31.977+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282332.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282332.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:31.998+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282258.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282258.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:32.044+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282034.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282034.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:32.073+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282022.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282022.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:32.098+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281819.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281819.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:32.202+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282018.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282018.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:32.241+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282346.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282346.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:32.280+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282038.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282038.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:32.301+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282254.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282254.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:32.313+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282002.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282002.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:32.327+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282110.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282110.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:32.344+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281803.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281803.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:32.364+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281946.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281946.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:32.383+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282106.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282106.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:32.422+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281950.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281950.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:32.442+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282014.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282014.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:32.458+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281843.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281843.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:32.479+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282042.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282042.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:32.500+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282054.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282054.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:32.529+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281438.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281438.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:32.557+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282214.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282214.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:32.604+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282306.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282306.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:32.752+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282310.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282310.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:32.781+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281300.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281300.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:32.826+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282202.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282202.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:32.849+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281838.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281838.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:32.871+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282330.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282330.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:32.901+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281232.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281232.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:32.937+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282222.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282222.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:32.959+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282058.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282058.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:32.978+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282234.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282234.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:33.573+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282218.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282218.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:33.608+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281930.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281930.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:33.634+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281926.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281926.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:33.664+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282340.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282340.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:33.685+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282252.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282252.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:33.708+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282028.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282028.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:33.741+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281741.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281741.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:33.760+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281346.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281346.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:33.787+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282004.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282004.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:33.816+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282116.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282116.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:33.831+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281413.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281413.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:33.871+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281940.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281940.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:33.906+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282100.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282100.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:33.945+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281956.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281956.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:33.980+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282157.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282157.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:34.010+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282012.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282012.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:34.038+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282032.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282032.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:34.098+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282024.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282024.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:34.123+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281825.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281825.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:34.166+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282008.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282008.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:34.217+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282336.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282336.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:34.245+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282048.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282048.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:34.283+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281234.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281234.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:34.350+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282224.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282224.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:34.376+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282232.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282232.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:34.394+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282320.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282320.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:34.424+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281936.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281936.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:34.505+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281920.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281920.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:34.606+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282208.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282208.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:34.660+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282228.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282228.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:34.716+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281238.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281238.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:34.742+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282044.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282044.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:34.780+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282052.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282052.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:34.822+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281916.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281916.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:34.868+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282212.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282212.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:34.893+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281828.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281828.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:34.915+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282300.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282300.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:34.961+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282316.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282316.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:34.979+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281306.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281306.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:35.003+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282204.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282204.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:35.028+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250227/202502272248.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250227/202502272248.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:35.045+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250227/202502272253.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250227/202502272253.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:35.058+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250227/202502272245.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250227/202502272245.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:35.084+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250227/202502272300.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250227/202502272300.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:35.101+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250227/202502272242.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250227/202502272242.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:35.121+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250227/202502272306.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250227/202502272306.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:35.138+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250227/202502272234.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250227/202502272234.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:35.156+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250227/202502272259.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250227/202502272259.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:35.206+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250227/202502272304.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250227/202502272304.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:35.220+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250227/202502272312.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250227/202502272312.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:35.236+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250227/202502272334.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250227/202502272334.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:35.795+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250227/202502272302.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250227/202502272302.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:21:36.798+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-03-02T19:21:36.860+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=api_to_db_dag, task_id=process_raw_velib_station, execution_date=20250302T192112, start_date=20250302T192124, end_date=20250302T192136
[2025-03-02T19:21:36.947+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-03-02T19:21:37.059+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
