[2025-03-02T21:15:06.356+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_db_dag.combine_analyse_data scheduled__2025-03-02T21:00:00+00:00 [queued]>
[2025-03-02T21:15:06.368+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_db_dag.combine_analyse_data scheduled__2025-03-02T21:00:00+00:00 [queued]>
[2025-03-02T21:15:06.368+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-03-02T21:15:06.377+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): combine_analyse_data> on 2025-03-02 21:00:00+00:00
[2025-03-02T21:15:06.384+0000] {standard_task_runner.py:57} INFO - Started process 2356 to run task
[2025-03-02T21:15:06.387+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_to_db_dag', 'combine_analyse_data', 'scheduled__2025-03-02T21:00:00+00:00', '--job-id', '274', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpy6xmlvlv']
[2025-03-02T21:15:06.389+0000] {standard_task_runner.py:85} INFO - Job 274: Subtask combine_analyse_data
[2025-03-02T21:15:06.440+0000] {task_command.py:410} INFO - Running <TaskInstance: api_to_db_dag.combine_analyse_data scheduled__2025-03-02T21:00:00+00:00 [running]> on host e1321964fd20
[2025-03-02T21:15:06.526+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_to_db_dag' AIRFLOW_CTX_TASK_ID='combine_analyse_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T21:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-02T21:00:00+00:00'
[2025-03-02T21:15:09.242+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/pyspark/context.py:317 FutureWarning: Python 3.7 support is deprecated in Spark 3.4.
[2025-03-02T21:15:14.747+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-03-02T21:15:14.759+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=api_to_db_dag, task_id=combine_analyse_data, execution_date=20250302T210000, start_date=20250302T211506, end_date=20250302T211514
[2025-03-02T21:15:14.816+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-03-02T21:15:14.851+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
