[2025-03-02T21:00:06.029+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_db_dag.process_raw_velib_station scheduled__2025-03-02T20:45:00+00:00 [queued]>
[2025-03-02T21:00:06.037+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_db_dag.process_raw_velib_station scheduled__2025-03-02T20:45:00+00:00 [queued]>
[2025-03-02T21:00:06.038+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-03-02T21:00:06.048+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): process_raw_velib_station> on 2025-03-02 20:45:00+00:00
[2025-03-02T21:00:06.054+0000] {standard_task_runner.py:57} INFO - Started process 330 to run task
[2025-03-02T21:00:06.057+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_to_db_dag', 'process_raw_velib_station', 'scheduled__2025-03-02T20:45:00+00:00', '--job-id', '265', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpina7g71z']
[2025-03-02T21:00:06.059+0000] {standard_task_runner.py:85} INFO - Job 265: Subtask process_raw_velib_station
[2025-03-02T21:00:06.096+0000] {task_command.py:410} INFO - Running <TaskInstance: api_to_db_dag.process_raw_velib_station scheduled__2025-03-02T20:45:00+00:00 [running]> on host e1321964fd20
[2025-03-02T21:00:06.168+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_to_db_dag' AIRFLOW_CTX_TASK_ID='process_raw_velib_station' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T20:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-02T20:45:00+00:00'
[2025-03-02T21:00:06.205+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011730.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011730.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.220+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503010009.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503010009.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.299+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011100.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011100.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.311+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011415.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011415.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.322+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011045.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011045.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.336+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011815.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011815.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.352+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503010005.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503010005.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.372+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503010012.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503010012.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.387+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011615.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011615.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.399+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011245.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011245.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.411+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503010004.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503010004.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.425+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011300.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011300.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.439+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011930.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011930.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.449+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011530.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011530.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.464+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503012035.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503012035.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.521+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011215.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011215.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.537+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011645.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011645.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.554+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011130.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011130.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.572+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011330.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011330.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.810+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503010940.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503010940.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.826+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503010002.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503010002.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.836+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503010901.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503010901.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.852+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011845.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011845.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.864+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011900.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011900.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.877+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011500.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011500.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.889+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011015.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011015.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.900+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011445.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011445.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.925+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011702.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011702.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.941+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503010902.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503010902.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.974+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011000.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011000.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.984+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011515.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011515.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:06.994+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011145.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011145.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.006+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011915.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011915.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.019+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011630.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011630.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.045+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011830.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011830.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.060+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011430.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011430.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.073+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503010000.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503010000.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.084+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011715.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011715.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.095+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011345.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011345.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.104+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011200.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011200.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.134+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011030.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011030.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.178+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011548.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011548.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.193+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011315.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011315.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.209+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011745.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011745.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.223+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011600.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011600.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.241+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503010011.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503010011.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.256+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503010945.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503010945.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.321+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011945.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011945.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.343+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011800.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011800.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.384+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011400.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011400.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.404+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011115.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011115.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.425+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503010006.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503010006.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.471+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503010010.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503010010.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.520+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250301/202503011230.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250301/202503011230.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.549+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282010.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282010.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.650+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281954.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281954.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.662+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282102.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282102.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.671+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281942.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281942.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.680+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282114.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282114.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.689+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281915.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281915.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.698+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282006.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282006.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.708+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282342.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282342.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.718+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281958.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281958.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.795+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281348.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281348.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.804+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282026.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282026.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.818+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282030.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282030.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.830+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282318.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282318.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.840+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281922.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281922.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.848+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281758.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281758.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.858+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281934.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281934.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.871+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282359.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282359.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.889+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281918.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281918.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.904+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282322.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282322.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.918+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282230.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282230.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.958+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282158.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282158.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.971+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282206.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282206.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:07.987+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282314.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282314.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.015+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282302.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282302.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.029+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281938.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281938.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.043+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282210.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282210.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.058+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282050.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282050.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.076+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281739.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281739.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.093+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282046.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282046.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.112+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282338.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282338.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.125+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281909.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281909.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.138+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281231.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281231.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.160+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282108.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282108.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.171+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281732.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281732.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.186+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281948.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281948.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.205+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282020.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282020.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.216+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282036.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282036.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.228+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282016.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282016.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.240+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281952.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281952.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.255+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281817.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281817.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.277+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282104.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282104.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.297+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281728.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281728.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.307+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281944.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281944.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.318+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282112.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282112.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.334+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282000.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282000.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.347+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282256.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282256.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.362+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282344.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282344.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.378+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281354.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281354.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.391+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282200.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282200.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.403+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282312.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282312.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.414+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281928.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281928.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.512+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282304.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282304.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.522+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282216.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282216.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.533+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281338.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281338.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.546+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282328.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282328.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.578+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282056.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282056.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.620+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282040.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282040.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.664+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281924.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281924.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.683+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282308.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282308.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.696+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281932.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281932.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.705+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281436.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281436.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.714+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282324.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282324.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.724+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282236.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282236.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.734+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282220.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282220.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.746+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282332.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282332.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.769+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282258.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282258.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.780+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282034.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282034.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.792+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282022.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282022.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.802+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281819.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281819.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.813+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282018.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282018.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.823+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282346.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282346.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.836+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282038.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282038.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.845+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282254.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282254.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.856+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282002.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282002.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.867+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282110.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282110.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.879+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281803.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281803.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.895+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281946.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281946.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.912+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282106.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282106.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.923+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281950.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281950.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.934+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282014.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282014.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.945+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281843.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281843.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.957+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282042.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282042.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.968+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282054.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282054.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.979+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281438.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281438.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.989+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282214.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282214.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:08.999+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282306.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282306.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.009+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282310.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282310.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.020+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281300.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281300.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.031+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282202.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282202.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.041+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281838.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281838.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.051+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282330.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282330.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.061+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281232.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281232.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.072+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282222.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282222.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.083+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282058.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282058.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.098+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282234.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282234.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.352+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282218.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282218.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.363+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281930.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281930.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.377+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281926.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281926.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.388+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282340.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282340.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.401+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282252.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282252.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.411+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282028.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282028.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.422+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281741.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281741.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.432+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281346.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281346.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.442+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282004.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282004.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.451+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282116.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282116.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.461+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281413.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281413.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.470+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281940.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281940.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.480+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282100.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282100.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.491+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281956.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281956.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.506+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282157.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282157.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.522+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282012.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282012.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.533+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282032.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282032.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.547+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282024.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282024.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.560+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281825.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281825.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.572+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282008.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282008.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.584+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282336.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282336.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.596+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282048.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282048.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.607+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281234.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281234.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.617+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282224.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282224.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.630+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282232.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282232.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.641+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282320.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282320.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.684+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281936.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281936.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.802+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281920.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281920.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.852+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282208.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282208.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.886+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282228.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282228.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.909+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281238.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281238.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.935+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282044.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282044.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.952+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282052.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282052.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.966+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281916.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281916.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.979+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282212.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282212.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:09.992+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281828.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281828.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:10.004+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282300.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282300.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:10.026+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282316.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282316.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:10.047+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502281306.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502281306.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:10.077+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250228/202502282204.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250228/202502282204.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:10.094+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250227/202502272248.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250227/202502272248.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:10.107+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250227/202502272253.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250227/202502272253.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:10.119+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250227/202502272245.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250227/202502272245.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:10.130+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250227/202502272300.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250227/202502272300.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:10.140+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250227/202502272242.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250227/202502272242.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:10.151+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250227/202502272306.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250227/202502272306.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:10.161+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250227/202502272234.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250227/202502272234.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:10.173+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250227/202502272259.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250227/202502272259.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:10.183+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250227/202502272304.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250227/202502272304.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:10.193+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250227/202502272312.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250227/202502272312.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:10.203+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250227/202502272334.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250227/202502272334.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:10.344+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/velib_stations/20250227/202502272302.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/velib_stations/20250227/202502272302.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T21:00:11.071+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-03-02T21:00:11.078+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=api_to_db_dag, task_id=process_raw_velib_station, execution_date=20250302T204500, start_date=20250302T210006, end_date=20250302T210011
[2025-03-02T21:00:11.126+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-03-02T21:00:11.171+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
