[2025-03-02T19:45:05.364+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_db_dag.process_raw_station_information scheduled__2025-03-02T19:30:00+00:00 [queued]>
[2025-03-02T19:45:05.372+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_db_dag.process_raw_station_information scheduled__2025-03-02T19:30:00+00:00 [queued]>
[2025-03-02T19:45:05.372+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-03-02T19:45:05.382+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): process_raw_station_information> on 2025-03-02 19:30:00+00:00
[2025-03-02T19:45:05.389+0000] {standard_task_runner.py:57} INFO - Started process 87711 to run task
[2025-03-02T19:45:05.391+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_to_db_dag', 'process_raw_station_information', 'scheduled__2025-03-02T19:30:00+00:00', '--job-id', '222', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmphk6esekl']
[2025-03-02T19:45:05.395+0000] {standard_task_runner.py:85} INFO - Job 222: Subtask process_raw_station_information
[2025-03-02T19:45:05.431+0000] {task_command.py:410} INFO - Running <TaskInstance: api_to_db_dag.process_raw_station_information scheduled__2025-03-02T19:30:00+00:00 [running]> on host 3befbd719c1b
[2025-03-02T19:45:05.503+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_to_db_dag' AIRFLOW_CTX_TASK_ID='process_raw_station_information' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T19:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-02T19:30:00+00:00'
[2025-03-02T19:45:05.528+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011730.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011730.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.538+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503010009.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503010009.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.573+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011100.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011100.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.580+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011415.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011415.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.586+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011045.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011045.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.593+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011815.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011815.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.599+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503010005.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503010005.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.605+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503010012.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503010012.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.612+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011615.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011615.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.618+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011245.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011245.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.624+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503010004.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503010004.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.631+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011300.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011300.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.638+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011930.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011930.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.644+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011530.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011530.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.650+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503012035.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503012035.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.684+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011215.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011215.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.695+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011645.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011645.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.702+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011130.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011130.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.710+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011330.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011330.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.737+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503010940.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503010940.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.745+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503010002.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503010002.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.752+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503010901.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503010901.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.759+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011845.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011845.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.765+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011900.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011900.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.771+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011500.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011500.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.778+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011015.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011015.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.786+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011445.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011445.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.794+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011702.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011702.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.802+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503010902.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503010902.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.820+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011000.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011000.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.828+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011515.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011515.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.836+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011145.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011145.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.844+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011915.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011915.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.854+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011630.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011630.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.876+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011830.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011830.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.885+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011430.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011430.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.892+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503010000.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503010000.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.899+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011715.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011715.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.907+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011345.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011345.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.914+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011200.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011200.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.934+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011030.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011030.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.953+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011548.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011548.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.961+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011315.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011315.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.968+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011745.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011745.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.976+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011600.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011600.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.984+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503010011.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503010011.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:05.991+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503010945.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503010945.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.020+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011945.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011945.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.027+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011800.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011800.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.042+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011400.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011400.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.049+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011115.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011115.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.055+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503010006.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503010006.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.247+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503010010.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503010010.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.265+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250301/202503011230.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250301/202503011230.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.283+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282010.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282010.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.290+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281954.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281954.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.297+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282102.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282102.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.303+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281942.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281942.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.310+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282114.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282114.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.317+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281915.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281915.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.323+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282006.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282006.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.329+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282342.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282342.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.336+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281958.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281958.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.342+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281348.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281348.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.349+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282026.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282026.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.356+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282030.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282030.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.362+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282318.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282318.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.369+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281922.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281922.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.375+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281758.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281758.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.381+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281934.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281934.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.388+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282359.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282359.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.396+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281918.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281918.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.403+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282322.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282322.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.413+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282230.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282230.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.432+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282226.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282226.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.441+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281324.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281324.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.459+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282158.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282158.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.468+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282206.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282206.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.476+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282314.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282314.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.485+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282302.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282302.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.496+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281938.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281938.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.504+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282210.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282210.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.511+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282050.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282050.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.517+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281739.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281739.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.523+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282046.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282046.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.529+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282338.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282338.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.535+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281909.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281909.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.541+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281231.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281231.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.548+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281724.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281724.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.554+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282108.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282108.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.560+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281732.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281732.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.567+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281948.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281948.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.574+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282020.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282020.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.580+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282036.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282036.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.587+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282016.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282016.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.593+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281952.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281952.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.599+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281817.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281817.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.606+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282104.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282104.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.612+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281728.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281728.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.618+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281944.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281944.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.625+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282112.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282112.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.631+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282000.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282000.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.638+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282256.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282256.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.644+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282344.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282344.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.651+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281354.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281354.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.658+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282200.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282200.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.664+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282312.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282312.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.672+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281928.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281928.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.679+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282304.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282304.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.685+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282216.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282216.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.691+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281338.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281338.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.698+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282328.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282328.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.704+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282056.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282056.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.710+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282040.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282040.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.717+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281924.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281924.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.723+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282308.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282308.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.729+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281932.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281932.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.736+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281436.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281436.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.742+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282324.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282324.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.749+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282236.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282236.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.755+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282220.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282220.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.761+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282332.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282332.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.768+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282258.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282258.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.775+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282034.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282034.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.782+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282022.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282022.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.789+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281819.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281819.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.795+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282018.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282018.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.801+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282346.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282346.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.808+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282038.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282038.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.814+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282254.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282254.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.820+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282002.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282002.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.827+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282110.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282110.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.834+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281803.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281803.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.840+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281946.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281946.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.846+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282106.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282106.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.854+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281950.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281950.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.864+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282014.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282014.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.874+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281843.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281843.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.882+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282042.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282042.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.889+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282054.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282054.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.896+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281438.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281438.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.903+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282214.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282214.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.910+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282306.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282306.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.918+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282310.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282310.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.924+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281300.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281300.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.931+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282202.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282202.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.938+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281838.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281838.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.945+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282330.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282330.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.953+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281232.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281232.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.960+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282222.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282222.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.968+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282058.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282058.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.975+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282234.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282234.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.982+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282326.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282326.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.990+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282218.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282218.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:06.997+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281930.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281930.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.004+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281926.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281926.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.010+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282340.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282340.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.017+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282252.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282252.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.023+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282028.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282028.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.032+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281741.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281741.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.040+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281346.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281346.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.047+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282004.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282004.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.055+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282116.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282116.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.062+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281413.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281413.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.070+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281940.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281940.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.077+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282100.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282100.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.084+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281956.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281956.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.091+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282157.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282157.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.098+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282012.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282012.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.106+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282032.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282032.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.113+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282024.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282024.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.120+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281825.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281825.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.127+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282008.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282008.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.134+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282336.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282336.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.140+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282048.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282048.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.147+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281234.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281234.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.153+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282224.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282224.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.161+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282232.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282232.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.168+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282320.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282320.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.175+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281936.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281936.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.181+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281920.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281920.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.187+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282208.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282208.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.194+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282228.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282228.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.201+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281238.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281238.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.211+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282044.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282044.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.308+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282052.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282052.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.317+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281916.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281916.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.324+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282212.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282212.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.330+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281828.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281828.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.337+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282300.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282300.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.344+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282316.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282316.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.350+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502281306.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502281306.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.357+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250228/202502282204.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250228/202502282204.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.364+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250227/202502272248.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250227/202502272248.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.370+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250227/202502272253.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250227/202502272253.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.376+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250227/202502272245.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250227/202502272245.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.383+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250227/202502272300.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250227/202502272300.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.390+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250227/202502272242.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250227/202502272242.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.396+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250227/202502272306.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250227/202502272306.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.402+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250227/202502272234.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250227/202502272234.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.409+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250227/202502272259.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250227/202502272259.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.418+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250227/202502272304.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250227/202502272304.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.425+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250227/202502272312.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250227/202502272312.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.432+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250227/202502272334.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250227/202502272334.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.442+0000] {logging_mixin.py:149} INFO - Error processing file /mnt/data/raw/velib_api/station_information/20250227/202502272302.json: [Errno 21] Failed to open local file '/mnt/data/formatted/velib_api/station_information/20250227/202502272302.snappy.parquet'. Detail: [errno 21] Is a directory
[2025-03-02T19:45:07.798+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-03-02T19:45:07.807+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=api_to_db_dag, task_id=process_raw_station_information, execution_date=20250302T193000, start_date=20250302T194505, end_date=20250302T194507
[2025-03-02T19:45:07.824+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-03-02T19:45:07.845+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
